---
- hosts: all
  sudo: yes
  tasks:
  - name: install ntpdate
    package:
     name: nginx
     state: present

  - template:
     src: index.nginx-debian.html
     dest: /var/www/html/index.nginx-debian.html
     owner: root
     mode: "u=rw,g=r,o=r"
