---
- hosts: brooklyn
  remote_user: root
  vars:
    download_url: https://ipfs.subutai.io/ipfs/QmUFYHDnWv2t2wT1JgWnjrpk5PRtmEum82i24beLpZ68XF/jdk-8u201-linux-x64.ta$
    download_folder: /opt
    java_archive: "{{download_folder}}/jdk-8u201-linux-x64.tar.gz"

  tasks:
  - name: Download Java
    command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept$

  - name: Unarchive java
    unarchive:
      src={{ java_archive }}
      dest={{download_folder}}
      remote_src=yes

   - name: Clean up
     file: state=absent path={{java_archive}}


   - name: Set JAVA_HOME
     lineinfile:
      dest: /etc/environment
      state: present
      regexp: '^JAVA_HOME'
      line: 'JAVA_HOME=/opt/jdk1.8.0_201'
