---
- hosts: all
  sudo: yes
  tasks:
     - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true
        
    - name: Install dirmngr
      apt:
        name: nginx
        state: present
